[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "speech_tokenizer"
version = "0.1.0"
description = "speech_tokenizer_repository"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "numpy",
    "scipy",
    "soundfile",
    "pandas",
    "librosa",
    "numba>=0.59",
    "tqdm",
    "lightning",
    "torchmetrics",
    "pystoi",
    "transformers",
    "einops",
    "beartype",
    "tensorboard",
    "accelerate",
]

[project.optional-dependencies]
cpu = [
  "torch",
  "torchvision",
  "torchaudio",
  "torchcodec"
]
cu128 = [
  "torch",
  "torchvision",
  "torchaudio",
  "torchcodec"
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
# By providing multiple options for the same package, uv will select 
# the one that matches the index provided via the CLI.
torch = [
  { index = "pytorch-cu128", extra = "cu128"},
  { index = "pytorch-cpu", extra = "cpu"},
]
torchvision = [
  { index = "pytorch-cu128", extra = "cu128"},
  { index = "pytorch-cpu", extra = "cpu"},
]
torchaudio = [
  { index = "pytorch-cu128", extra = "cu128"},
  { index = "pytorch-cpu", extra = "cpu"},
]
# Always pull torchcodec from CPU index regardless of the global choice
torchcodec = [
  { index = "pytorch-cpu", extra = "cu128"},
  { index = "pytorch-cpu", extra = "cpu"},
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.ty.environment]
root = ["./src"]